"""Sphinx configuration.

One page per public object, generated by autosummary: signature, prose,
arguments, and a runnable example.
Examples are not decorative -- ``make doctest`` executes every one of them, and so
does ``pytest --doctest-modules``, so an example that stops working fails the
build rather than quietly misleading somebody.
"""

from __future__ import annotations

import os
import sys
from datetime import date

sys.path.insert(0, os.path.abspath("../src"))

import nilmframe  # noqa: E402

project = "nilmframe"
author = "Ilia Kamyshev"
copyright = f"{date.today().year}, {author}"
release = nilmframe.__version__
version = release

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx.ext.mathjax",
    "sphinx_copybutton",
    "sphinx_design",
    "myst_parser",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}

# `:::{directive}` is MyST's colon fence, and it is off unless asked for -- so
# without this every admonition and every sphinx-design card on the site renders
# as its own literal source text, silently and without a build warning. That is
# the syntax sphinx-design's own documentation uses, which is how it got here.
myst_enable_extensions = ["colon_fence"]

# -- autodoc / autosummary --------------------------------------------------- #

autosummary_generate = True
autosummary_imported_members = False
autodoc_member_order = "groupwise"
autodoc_typehints = "signature"
autodoc_typehints_description_target = "documented"
autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "show-inheritance": True,
    "member-order": "groupwise",
    # `training`, `dump_patches` and friends are torch.nn.Module's bookkeeping.
    # They appeared under "Attributes" on every transform page and told a reader
    # nothing about the transform.
    "exclude-members": (
        "training, dump_patches, call_super_init, T_destination, forward_pre_hooks, "
        "add_module, apply, bfloat16, buffers, children, compile, cpu, cuda, double, "
        "eval, extra_repr, float, get_buffer, get_extra_state, get_parameter, "
        "get_submodule, half, ipu, load_state_dict, modules, mtia, named_buffers, "
        "named_children, named_modules, named_parameters, parameters, "
        "register_backward_hook, register_buffer, register_forward_hook, "
        "register_forward_pre_hook, register_full_backward_hook, "
        "register_full_backward_pre_hook, register_load_state_dict_post_hook, "
        "register_load_state_dict_pre_hook, register_module, register_parameter, "
        "register_state_dict_post_hook, register_state_dict_pre_hook, "
        "requires_grad_, set_extra_state, set_submodule, share_memory, "
        "state_dict, to, to_empty, type, xpu, zero_grad"
    ),
}
# torch.nn.Module drags ~80 inherited methods into every transform page and buries
# the two that matter.
autodoc_inherit_docstrings = False
autodoc_mock_imports = ["lightning"]

napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_use_param = True
napoleon_use_rtype = False
napoleon_preprocess_types = True
# Dataclass fields are otherwise described twice: once by the docstring's
# `Attributes:` section and once by autodoc walking the annotations.
napoleon_use_ivar = True

# Enum subclasses otherwise show `(value, names=<not given>, *values, module=None,
# ...)` -- EnumMeta's own signature, which describes nothing about the enum.
autodoc_class_signature = "separated"

# -- doctest ----------------------------------------------------------------- #

# Collect plain `>>>` blocks too, not only `.. doctest::` directives, so an
# example written in a narrative page is executed like the docstring ones.
doctest_test_doctest_blocks = "default"

# Every page's examples run against one small store, built once. Examples that
# need real data therefore stay real without shipping a fixture in the repo.
doctest_global_setup = """
import warnings; warnings.filterwarnings("ignore")
import numpy as np, torch
import nilmframe as nf
from nilmframe.docdata import example_store, example_measurement
store = example_store()
"""

# -- intersphinx ------------------------------------------------------------- #

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "torch": ("https://pytorch.org/docs/stable", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "pandas": ("https://pandas.pydata.org/docs", None),
}

# -- HTML -------------------------------------------------------------------- #

html_theme = "furo"
html_title = f"nilmframe {release}"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_show_sourcelink = True

# One file for both colour schemes: the mark is a pure gradient with no neutral in
# it, so there is no ink that would need inverting on a dark page. Regenerate with
# `python docs/_scripts/make_logo.py docs/_static`.
html_logo = "_static/logo.svg"
html_favicon = "_static/favicon.svg"

html_theme_options = {
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "light_css_variables": {
        "color-brand-primary": "#C2410C",
        "color-brand-content": "#C2410C",
        # Furo's own violet was showing through on visited links; make it the
        # tile's violet so it reads as a decision rather than a leftover.
        "color-link--visited": "#7C3AED",
        "color-link--visited--hover": "#7C3AED",
        "font-stack": "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        "font-stack--monospace": "'JetBrains Mono', 'SF Mono', Menlo, monospace",
    },
    "dark_css_variables": {
        "color-brand-primary": "#FBBF24",
        "color-brand-content": "#FBBF24",
        "color-link--visited": "#A78BFA",
        "color-link--visited--hover": "#A78BFA",
    },
    "source_repository": "https://github.com/arx7ti/nilmframe",
    "source_branch": "main",
    "source_directory": "docs/",
}
